//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset()
        {
            this.Requests = new HashSet<Request>();
        }

        public int Ast_Id { get; set; }
        [Required(ErrorMessage = "Serial Number field is required")]
        public string Ser_Num { get; set; }
        [Required(ErrorMessage = "Model Number field is required")]
        public string Mod_Num { get; set; }
        [Required(ErrorMessage = "Asset Type field is required")]
        public string Ast_Type { get; set; }
        [Required(ErrorMessage = "Cost field is required")]
        public Nullable<int> Cost { get; set; }
        public System.DateTime Date { get; set; }
        public string Created_By { get; set; }
        public string Updated_By { get; set; }
        public System.DateTime Created_At { get; set; }
        public System.DateTime Updated_At { get; set; }
        public bool Is_Active { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<Request> Requests { get; set; }
    }
}
