//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Req_Id { get; set; }
        public int Usr_Id { get; set; }
        public int Ast_Id { get; set; }
        public int Req_Status { get; set; }
        public string Created_By { get; set; }
        public string Updated_By { get; set; }
        public System.DateTime Created_At { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
        public string Priority { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual User User { get; set; }
    }
}
